"""Collection, reduction, recursion, and lazy-sequence runtime helpers."""

from __future__ import annotations

from ._sequence_consumers import *
from ._sequence_core import *
from ._sequence_eager import *
from ._sequence_partitions import *
from ._sequence_transforms import *

__all__ = [
    "Reduced",
    "coll_q",
    "concat",
    "cons",
    "count",
    "cycle",
    "dedupe",
    "distinct",
    "doall",
    "dorun",
    "doseq",
    "drop",
    "drop_last",
    "drop_while",
    "empty",
    "empty_q",
    "every_q",
    "filter",
    "filterv",
    "first",
    "fold",
    "for_stop",
    "interleave",
    "interpose",
    "iterate",
    "keep",
    "keep_indexed",
    "lazy_seq",
    "loop",
    "map",
    "map_indexed",
    "mapcat",
    "mapcatv",
    "mapv",
    "next",
    "nonempty",
    "not_any_q",
    "not_every_q",
    "nth",
    "partition",
    "partition_all",
    "partition_by",
    "recur",
    "reduce",
    "reduced",
    "reduced_p",
    "reductions",
    "remove",
    "removev",
    "repeat",
    "repeatedly",
    "rest",
    "run_bang",
    "seq",
    "seq_q",
    "sequence",
    "sequential_q",
    "some",
    "take",
    "take_last",
    "take_while",
    "trampoline",
    "unreduced",
]
