use serde::Serialize;

use super::CliOutcome;

const REGISTRY_SCHEMA: &str = "osiris.cli-commands/v1";

#[derive(Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct ArgumentDefinition {
    name: &'static str,
    value_type: &'static str,
    required: bool,
    multiple: bool,
    summary: &'static str,
}

#[derive(Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct OptionDefinition {
    name: &'static str,
    aliases: &'static [&'static str],
    value_type: &'static str,
    default: Option<&'static str>,
    multiple: bool,
    conflicts: &'static [&'static str],
    precedence: &'static str,
    summary: &'static str,
}

#[derive(Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct CommandDefinition {
    id: &'static str,
    name: &'static str,
    aliases: &'static [&'static str],
    lifecycle: &'static str,
    summary: &'static str,
    synopsis: &'static str,
    positionals: &'static [ArgumentDefinition],
    options: &'static [OptionDefinition],
    input: &'static str,
    output: &'static str,
    stdout: &'static str,
    stderr: &'static str,
    formats: &'static [&'static str],
    filesystem_effects: &'static str,
    process_effects: &'static str,
    network_effects: &'static str,
    dependency_effects: &'static str,
    exit_codes: &'static [u8],
    interruption: &'static str,
    requirements: &'static [&'static str],
    diagnostics: &'static [&'static str],
    examples: &'static [&'static str],
}

const PATH: ArgumentDefinition = ArgumentDefinition {
    name: "path",
    value_type: "path",
    required: false,
    multiple: false,
    summary: "Project, directory, or source path selected by the command.",
};
const FILES: ArgumentDefinition = ArgumentDefinition {
    name: "file",
    value_type: "path",
    required: true,
    multiple: true,
    summary: "One or more explicit .osr source files.",
};
const PROJECT: ArgumentDefinition = ArgumentDefinition {
    name: "project",
    value_type: "path",
    required: true,
    multiple: false,
    summary: "Directory to create; optional only with --existing.",
};
const GRAPHQL: ArgumentDefinition = ArgumentDefinition {
    name: "graphql-document",
    value_type: "string-or-stdin-marker",
    required: true,
    multiple: false,
    summary: "One GraphQL query document, or - to read it from stdin.",
};
const OPERATION: ArgumentDefinition = ArgumentDefinition {
    name: "operation",
    value_type: "lsc-operation",
    required: true,
    multiple: false,
    summary: "A finite local language-service operation and its operands.",
};

const SITE_ROOT: OptionDefinition = OptionDefinition {
    name: "--site-root",
    aliases: &[],
    value_type: "path",
    default: None,
    multiple: true,
    conflicts: &[],
    precedence: "command line",
    summary: "Add an installed-package discovery root.",
};
const JSON_FORMAT: OptionDefinition = OptionDefinition {
    name: "--format",
    aliases: &[],
    value_type: "text|json",
    default: Some("text"),
    multiple: false,
    conflicts: &[],
    precedence: "command line",
    summary: "Select human-readable text or stable JSON output.",
};

const COMMANDS: &[CommandDefinition] = &[
    CommandDefinition {
        id: "cli/init",
        name: "init",
        aliases: &[],
        lifecycle: "active",
        summary: "Create a project or add Osiris to an existing uv project.",
        synopsis: "osr init [--existing] [--extension] <project>",
        positionals: &[PROJECT],
        options: &[
            OptionDefinition {
                name: "--existing",
                aliases: &[],
                value_type: "bool",
                default: Some("false"),
                multiple: false,
                conflicts: &[],
                precedence: "command line",
                summary: "Configure an existing uv project; project defaults to .",
            },
            OptionDefinition {
                name: "--extension",
                aliases: &[],
                value_type: "bool",
                default: Some("false"),
                multiple: false,
                conflicts: &[],
                precedence: "command line",
                summary: "Configure the project as a publishable Osiris extension.",
            },
        ],
        input: "A target directory and, for --existing, its pyproject.toml.",
        output: "A uv-compatible project with osiris.jsonc and starter source.",
        stdout: "Created path and next command.",
        stderr: "Validation and uv failures.",
        formats: &["text"],
        filesystem_effects: "Creates or updates project configuration and starter source.",
        process_effects: "May run uv init and uv add.",
        network_effects: "uv may access configured package indexes.",
        dependency_effects: "Adds a compatible osiris-lang development/build requirement.",
        exit_codes: &[0, 1, 2],
        interruption: "Stops child uv and uses the platform interruption status.",
        requirements: &["OEP-0002-R012", "OEP-0002-R015"],
        diagnostics: &["OSR-C0001"],
        examples: &[
            "osr init demo",
            "osr init --existing .",
            "osr init --extension demo-ext",
        ],
    },
    CommandDefinition {
        id: "cli/check",
        name: "check",
        aliases: &[],
        lifecycle: "active",
        summary: "Analyze a project or source without generating artifacts.",
        synopsis: "osr check [path] [--site-root <path>]...",
        positionals: &[PATH],
        options: &[SITE_ROOT],
        input: "Configured source and validated static interfaces.",
        output: "Diagnostics only.",
        stdout: "Empty on success.",
        stderr: "Source and configuration diagnostics.",
        formats: &["text"],
        filesystem_effects: "Read-only.",
        process_effects: "None.",
        network_effects: "None.",
        dependency_effects: "Validates but does not modify locked dependencies.",
        exit_codes: &[0, 1, 2],
        interruption: "Stops promptly with the platform interruption status.",
        requirements: &["OEP-0002-R018"],
        diagnostics: &["OSR-C0001", "OSR-H0001"],
        examples: &["osr check", "osr check src/main.osr"],
    },
    CommandDefinition {
        id: "cli/build",
        name: "build",
        aliases: &[],
        lifecycle: "active",
        summary: "Compile the complete configured project into outDir.",
        synopsis: "osr build [directory] [--site-root <path>]...",
        positionals: &[PATH],
        options: &[SITE_ROOT],
        input: "Project sources, config, lock data, and static interfaces.",
        output: "Python, .osri, source maps, records, and linked support.",
        stdout: "Output directory.",
        stderr: "Build diagnostics.",
        formats: &["text"],
        filesystem_effects: "Atomically publishes configured build artifacts.",
        process_effects: "None.",
        network_effects: "None.",
        dependency_effects: "Validates but does not modify dependencies.",
        exit_codes: &[0, 1, 2],
        interruption: "Leaves no partial published artifact.",
        requirements: &["OEP-0002-R019", "OEP-0003-R069"],
        diagnostics: &["OSR-C0001", "OSR-I0001"],
        examples: &["osr build", "osr build ."],
    },
    CommandDefinition {
        id: "cli/compile",
        name: "compile",
        aliases: &[],
        lifecycle: "active",
        summary: "Compile explicit source files with optional artifact selection.",
        synopsis: "osr compile <file>... [--out-dir <path>] [--emit <kind>]... [--site-root <path>]...",
        positionals: &[FILES],
        options: &[
            OptionDefinition {
                name: "--out-dir",
                aliases: &[],
                value_type: "path",
                default: Some("dist"),
                multiple: false,
                conflicts: &[],
                precedence: "command line then project config",
                summary: "Select the artifact directory.",
            },
            OptionDefinition {
                name: "--emit",
                aliases: &[],
                value_type: "python|interface|source-map|records",
                default: Some("python,interface,source-map"),
                multiple: true,
                conflicts: &[],
                precedence: "command line",
                summary: "Select emitted artifact kinds.",
            },
            SITE_ROOT,
        ],
        input: "Explicit .osr sources and validated interfaces.",
        output: "Selected compiler artifacts and private linked support.",
        stdout: "Output directory.",
        stderr: "Compiler diagnostics.",
        formats: &["text"],
        filesystem_effects: "Atomically writes selected artifacts.",
        process_effects: "None.",
        network_effects: "None.",
        dependency_effects: "Read-only validation.",
        exit_codes: &[0, 1, 2],
        interruption: "Leaves no partial published artifact.",
        requirements: &["OEP-0002-R020", "OEP-0003-R070"],
        diagnostics: &["OSR-C0001", "OSR-I0001"],
        examples: &["osr compile src/main.osr --out-dir dist"],
    },
    CommandDefinition {
        id: "cli/watch",
        name: "watch",
        aliases: &[],
        lifecycle: "active",
        summary: "Rebuild when configured source inputs change.",
        synopsis: "osr watch [directory] [--site-root <path>]...",
        positionals: &[PATH],
        options: &[SITE_ROOT],
        input: "The configured source scope.",
        output: "Repeated complete project builds.",
        stdout: "Watch status and successful output directories.",
        stderr: "Build and watcher diagnostics.",
        formats: &["text"],
        filesystem_effects: "Writes the same artifacts as build.",
        process_effects: "Keeps a native filesystem watcher alive.",
        network_effects: "None.",
        dependency_effects: "Does not modify dependencies.",
        exit_codes: &[0, 1, 2, 130],
        interruption: "Ctrl-C releases watchers promptly and exits 130 on POSIX.",
        requirements: &["OEP-0002-R021", "OEP-0002-R022"],
        diagnostics: &["OSR-C0001"],
        examples: &["osr watch"],
    },
    CommandDefinition {
        id: "cli/run",
        name: "run",
        aliases: &[],
        lifecycle: "active",
        summary: "Compile and execute one Osiris source entry.",
        synopsis: "osr run <file> [--site-root <path>]... [-- <argument>...]",
        positionals: &[FILES],
        options: &[SITE_ROOT],
        input: "One source entry, its workspace, and program arguments.",
        output: "The invoked program's output and status.",
        stdout: "Program stdout.",
        stderr: "Compiler or program stderr.",
        formats: &["text"],
        filesystem_effects: "Uses and removes a private temporary build directory.",
        process_effects: "Starts target Python after successful compilation.",
        network_effects: "None.",
        dependency_effects: "Does not modify dependencies.",
        exit_codes: &[0, 1, 2],
        interruption: "Stops the child process; otherwise propagates its exit status.",
        requirements: &["OEP-0002-R023"],
        diagnostics: &["OSR-C0001"],
        examples: &["osr run src/main.osr -- input.csv"],
    },
    CommandDefinition {
        id: "cli/fmt",
        name: "fmt",
        aliases: &[],
        lifecycle: "active",
        summary: "Apply the one canonical Osiris source format.",
        synopsis: "osr fmt [path...] [--check] | osr fmt --all [--check] | osr fmt -",
        positionals: &[FILES],
        options: &[
            OptionDefinition {
                name: "--all",
                aliases: &[],
                value_type: "bool",
                default: Some("false"),
                multiple: false,
                conflicts: &["path", "-"],
                precedence: "command line",
                summary: "Explicitly select the complete configured project source scope.",
            },
            OptionDefinition {
                name: "--check",
                aliases: &[],
                value_type: "bool",
                default: Some("false"),
                multiple: false,
                conflicts: &["-"],
                precedence: "command line",
                summary: "Report non-canonical files without writing.",
            },
        ],
        input: ".osr files, project source scope, or stdin.",
        output: "Canonical UTF-8 source.",
        stdout: "Changed paths, or formatted stdin.",
        stderr: "Reader and formatting diagnostics.",
        formats: &["text"],
        filesystem_effects: "Safely replaces selected files unless --check or stdin is used.",
        process_effects: "None.",
        network_effects: "None.",
        dependency_effects: "None.",
        exit_codes: &[0, 1, 2],
        interruption: "Safe replacement preserves the original or complete new file.",
        requirements: &["OEP-0001-R073", "OEP-0001-R076"],
        diagnostics: &["OSR-R0001"],
        examples: &[
            "osr fmt src",
            "osr fmt --all",
            "osr fmt --all --check",
            "osr fmt -",
        ],
    },
    CommandDefinition {
        id: "cli/expand",
        name: "expand",
        aliases: &[],
        lifecycle: "active",
        summary: "Print macro-expanded Osiris syntax without executing Python.",
        synopsis: "osr expand <file> [--once]",
        positionals: &[FILES],
        options: &[OptionDefinition {
            name: "--once",
            aliases: &[],
            value_type: "bool",
            default: Some("false"),
            multiple: false,
            conflicts: &[],
            precedence: "command line",
            summary: "Expand one macro step.",
        }],
        input: "One .osr source.",
        output: "Expanded Osiris syntax and expansion diagnostics.",
        stdout: "Expanded source.",
        stderr: "Expansion diagnostics.",
        formats: &["text"],
        filesystem_effects: "Read-only.",
        process_effects: "None.",
        network_effects: "None.",
        dependency_effects: "None.",
        exit_codes: &[0, 1, 2],
        interruption: "Stops without modifying input.",
        requirements: &["OEP-0001-R034"],
        diagnostics: &["OSR-M0001"],
        examples: &["osr expand src/main.osr --once"],
    },
    CommandDefinition {
        id: "cli/lsc",
        name: "lsc",
        aliases: &[],
        lifecycle: "active",
        summary: "Query finite local language services without an editor protocol.",
        synopsis: "osr lsc <operation> ... [--locale <bcp47>] [--format text|json]",
        positionals: &[OPERATION],
        options: &[
            OptionDefinition {
                name: "--locale",
                aliases: &[],
                value_type: "bcp47",
                default: Some(":default"),
                multiple: false,
                conflicts: &[],
                precedence: "command line",
                summary: "Select an authored localized presentation.",
            },
            JSON_FORMAT,
        ],
        input: "Workspace source, overlays represented by paths, interfaces, or embedded standard records.",
        output: "Diagnostics, semantic facts, navigation, signatures, or edit previews.",
        stdout: "Requested text or one stable JSON object.",
        stderr: "Query and validation failures.",
        formats: &["text", "json"],
        filesystem_effects: "Read-only.",
        process_effects: "None.",
        network_effects: "None.",
        dependency_effects: "Read-only static discovery.",
        exit_codes: &[0, 1, 2],
        interruption: "Stops without modifying source.",
        requirements: &["OEP-0001-R066", "OEP-0001-R071"],
        diagnostics: &["OSR-L0001"],
        examples: &[
            "osr lsc hover osiris.core/map --locale zh-CN",
            "osr lsc diagnostics --format json",
        ],
    },
    CommandDefinition {
        id: "cli/lsp",
        name: "lsp",
        aliases: &[],
        lifecycle: "active",
        summary: "Run the Osiris Language Server over standard I/O.",
        synopsis: "osr lsp",
        positionals: &[],
        options: &[],
        input: "LSP JSON-RPC Content-Length frames on stdin.",
        output: "LSP JSON-RPC frames on stdout.",
        stdout: "Protocol transport only.",
        stderr: "Transport failures only.",
        formats: &["lsp-json-rpc"],
        filesystem_effects: "Read-only except editor-requested operations are previews.",
        process_effects: "Long-running stdio server.",
        network_effects: "None.",
        dependency_effects: "Read-only static discovery.",
        exit_codes: &[0, 1, 130],
        interruption: "Stops promptly and releases workspace state.",
        requirements: &["OEP-0001-R066", "OEP-0001-R077"],
        diagnostics: &["OSR-L0001"],
        examples: &[],
    },
    CommandDefinition {
        id: "cli/syntax",
        name: "syntax",
        aliases: &[],
        lifecycle: "active",
        summary: "Print the embedded complete English syntax manual.",
        synopsis: "osr syntax [--format markdown|json]",
        positionals: &[],
        options: &[OptionDefinition {
            name: "--format",
            aliases: &[],
            value_type: "markdown|json",
            default: Some("markdown"),
            multiple: false,
            conflicts: &[],
            precedence: "command line",
            summary: "Select complete Markdown or its versioned JSON projection.",
        }],
        input: "The release-pinned embedded documentation snapshot.",
        output: "The language/syntax document.",
        stdout: "Complete Markdown or one JSON object.",
        stderr: "Snapshot validation failures.",
        formats: &["markdown", "json"],
        filesystem_effects: "May materialize a verified read-only snapshot in the temporary directory.",
        process_effects: "None.",
        network_effects: "None.",
        dependency_effects: "None.",
        exit_codes: &[0, 1, 2],
        interruption: "Stops without changing documentation.",
        requirements: &["OEP-0001-R043"],
        diagnostics: &["OSR-D0001"],
        examples: &[],
    },
    CommandDefinition {
        id: "cli/doc",
        name: "doc",
        aliases: &[],
        lifecycle: "active",
        summary: "Execute one GraphQL query against embedded English documentation.",
        synopsis: "osr doc <graphql-document> | osr doc -",
        positionals: &[GRAPHQL],
        options: &[],
        input: "One GraphQL query argument or stdin document.",
        output: "A standard GraphQL response object.",
        stdout: "Exactly one GraphQL JSON response.",
        stderr: "CLI or embedded snapshot failures.",
        formats: &["graphql-json"],
        filesystem_effects: "May materialize a verified read-only snapshot in the temporary directory.",
        process_effects: "None.",
        network_effects: "None.",
        dependency_effects: "None.",
        exit_codes: &[0, 1, 2],
        interruption: "Stops without changing documentation.",
        requirements: &["OEP-0001-R045", "OEP-0001-R050"],
        diagnostics: &["OSR-D0001"],
        examples: &[
            "osr doc '{ documentationCapabilities { snapshotId schemaVersion } }'",
            "osr doc -",
        ],
    },
];

mod help;

pub(super) use help::{help_request, root_help};
